// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Task
type Task struct {
	// id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"index:,priority:3,composite:idx_tasks_status_deleted_at_id;primaryKey;autoIncrement;comment:id"`
	// task id
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty" gorm:"unique;size:128;comment:task id"`
	// task pid
	TaskPid string `protobuf:"bytes,3,opt,name=task_pid,json=taskPid,proto3" json:"task_pid,omitempty" gorm:"index;size:128;comment:task pid"`
	// uid
	Uid string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty" gorm:"index;size:128;comment:uid"`
	// other id
	OtherId string `protobuf:"bytes,5,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty" gorm:"index;size:128;comment:other id"`
	// cover
	Cover string `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty" gorm:"comment:cover"`
	// task name
	TaskName string `protobuf:"bytes,7,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty" gorm:"size:128;comment:task name"`
	// other type
	OtherType int32 `protobuf:"varint,9,opt,name=other_type,json=otherType,proto3" json:"other_type,omitempty" gorm:"index;size:4;comment:other type"`
	// other tag
	OtherTag int32 `protobuf:"varint,10,opt,name=other_tag,json=otherTag,proto3" json:"other_tag,omitempty" gorm:"index;size:4;comment:other tag"`
	// other form
	OtherForm int32 `protobuf:"varint,11,opt,name=other_form,json=otherForm,proto3" json:"other_form,omitempty" gorm:"index;size:4;comment:other form"`
	// other group
	OtherGroup int32 `protobuf:"varint,12,opt,name=other_group,json=otherGroup,proto3" json:"other_group,omitempty" gorm:"index;size:4;comment:other group"`
	// task type
	TaskType string `protobuf:"bytes,13,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty" gorm:"index;size:50;comment:task type"`
	// ciphertext
	Ciphertext string `protobuf:"bytes,14,opt,name=ciphertext,proto3" json:"ciphertext,omitempty" gorm:"comment:ciphertext"`
	// rewrite_hls
	RewriteHls []byte `protobuf:"bytes,15,opt,name=rewrite_hls,json=rewriteHls,proto3" json:"rewrite_hls,omitempty" gorm:"comment:rewrite hls"`
	// raw
	Raw []byte `protobuf:"bytes,21,opt,name=raw,proto3" json:"raw,omitempty" gorm:"comment:raw"`
	// message
	Message []byte `protobuf:"bytes,22,opt,name=message,proto3" json:"message,omitempty" gorm:"comment:message"`
	// message
	Statistics []byte `protobuf:"bytes,23,opt,name=statistics,proto3" json:"statistics,omitempty" gorm:"comment:statistics"`
	// status
	Status int32 `protobuf:"varint,24,opt,name=status,proto3" json:"status,omitempty" gorm:"index:,priority:1,composite:idx_tasks_status_deleted_at_id;default:1;size:2;comment:status 1 normal"`
	// created_at
	CreatedAt int64 `protobuf:"varint,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"index;comment:created at"`
	// updated_at
	UpdatedAt int64 `protobuf:"varint,26,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"index;comment:updated at"`
	// deleted_at
	DeletedAt int64 `protobuf:"varint,27,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"index:,priority:2,composite:idx_tasks_status_deleted_at_id;comment:deleted at"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Task.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return m.Size()
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Task) GetTaskPid() string {
	if m != nil {
		return m.TaskPid
	}
	return ""
}

func (m *Task) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Task) GetOtherId() string {
	if m != nil {
		return m.OtherId
	}
	return ""
}

func (m *Task) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Task) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Task) GetOtherType() int32 {
	if m != nil {
		return m.OtherType
	}
	return 0
}

func (m *Task) GetOtherTag() int32 {
	if m != nil {
		return m.OtherTag
	}
	return 0
}

func (m *Task) GetOtherForm() int32 {
	if m != nil {
		return m.OtherForm
	}
	return 0
}

func (m *Task) GetOtherGroup() int32 {
	if m != nil {
		return m.OtherGroup
	}
	return 0
}

func (m *Task) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *Task) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func (m *Task) GetRewriteHls() []byte {
	if m != nil {
		return m.RewriteHls
	}
	return nil
}

func (m *Task) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Task) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Task) GetStatistics() []byte {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *Task) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Task) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Task) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Task) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "Task")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 770 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x4d, 0x4f, 0x1b, 0x47,
	0x18, 0xc7, 0x59, 0x8c, 0xed, 0x7a, 0xa0, 0xad, 0x34, 0x6a, 0xe9, 0xe0, 0xaa, 0xbb, 0xdb, 0x45,
	0xb4, 0x6e, 0x4b, 0xa1, 0x06, 0xaa, 0x44, 0xb6, 0xa2, 0x08, 0x47, 0x81, 0x58, 0x89, 0xa2, 0x68,
	0xe5, 0x43, 0x94, 0x8b, 0x35, 0xec, 0x0c, 0xeb, 0x09, 0x5e, 0xcf, 0x66, 0x76, 0x36, 0xc6, 0xf9,
	0x00, 0x39, 0xe7, 0x1b, 0xe4, 0xeb, 0xe4, 0xc8, 0x31, 0xa7, 0x55, 0x02, 0xdf, 0x60, 0x4f, 0x39,
	0x46, 0x33, 0xbb, 0x06, 0x63, 0x99, 0x97, 0x9c, 0x98, 0x67, 0xf9, 0xff, 0x7f, 0xcf, 0x9b, 0xf4,
	0x18, 0x00, 0x89, 0xa3, 0xa3, 0x8d, 0x50, 0x70, 0xc9, 0xab, 0xff, 0xfa, 0x4c, 0xf6, 0xe2, 0x83,
	0x0d, 0x8f, 0x07, 0x9b, 0x3e, 0xf7, 0xf9, 0xa6, 0xfe, 0x7c, 0x10, 0x1f, 0xea, 0x48, 0x07, 0xfa,
	0x95, 0xc9, 0x9d, 0xf7, 0x4b, 0x60, 0xa1, 0x83, 0xa3, 0x23, 0x38, 0x02, 0xf3, 0x8c, 0x20, 0xc3,
	0x36, 0x6a, 0x85, 0x16, 0x4b, 0x13, 0x8b, 0xfa, 0x5c, 0x04, 0x0d, 0x87, 0x0d, 0x08, 0x3d, 0x6e,
	0xac, 0x87, 0x82, 0x71, 0xc1, 0xe4, 0xa8, 0xb1, 0xbd, 0xee, 0xf1, 0x20, 0xe4, 0x11, 0x93, 0xb4,
	0xc1, 0xc8, 0x71, 0x57, 0x65, 0x8e, 0xba, 0x91, 0xc4, 0x32, 0x8e, 0xba, 0x84, 0xf6, 0xa9, 0xa4,
	0xa4, 0x8b, 0x65, 0x97, 0x91, 0x66, 0x28, 0x58, 0x80, 0xc5, 0xe8, 0x31, 0x1d, 0x35, 0x71, 0x2c,
	0x79, 0x7b, 0xe0, 0x09, 0x1a, 0xd0, 0x81, 0x6c, 0x7a, 0x3c, 0x50, 0x7f, 0x1b, 0x8c, 0x38, 0xee,
	0x3c, 0x23, 0xf0, 0x01, 0x28, 0x2b, 0x4c, 0x97, 0x11, 0x34, 0x6f, 0x1b, 0xb5, 0x4a, 0xeb, 0xef,
	0x34, 0xb1, 0xfe, 0xc8, 0xf2, 0xc7, 0x03, 0xf6, 0x2a, 0xa6, 0xcd, 0x88, 0xbd, 0xa1, 0x8d, 0xfa,
	0xd6, 0xdd, 0x73, 0xaf, 0x32, 0xd8, 0x0a, 0x50, 0x52, 0xaf, 0x36, 0x81, 0x0f, 0xc1, 0x77, 0x1a,
	0x12, 0x32, 0x82, 0x0a, 0xd3, 0x14, 0xdd, 0xc5, 0x15, 0x90, 0x50, 0x51, 0x74, 0x01, 0xcf, 0x18,
	0x81, 0x77, 0x40, 0x21, 0x66, 0x04, 0x2d, 0x68, 0xc2, 0x5a, 0x9a, 0x58, 0xbf, 0x5f, 0x4b, 0x88,
	0x95, 0x59, 0x39, 0x54, 0x7e, 0x2e, 0x7b, 0x54, 0xa8, 0x2e, 0x8a, 0xb7, 0xcc, 0xaf, 0x0d, 0xba,
	0x8b, 0xb2, 0x7e, 0xb6, 0x09, 0xdc, 0x00, 0x45, 0x8f, 0xbf, 0xa6, 0x02, 0x95, 0x34, 0x03, 0xa5,
	0x89, 0xf5, 0x53, 0xc6, 0x18, 0x9b, 0xf4, 0xbf, 0x1d, 0x37, 0x93, 0xc1, 0x16, 0xa8, 0xe8, 0xb6,
	0x07, 0x38, 0xa0, 0xa8, 0x3c, 0x5d, 0xf5, 0xec, 0x8e, 0x95, 0xd6, 0x71, 0xf5, 0xb8, 0x9e, 0xe2,
	0x80, 0xc2, 0x36, 0x00, 0x59, 0xe9, 0x72, 0x14, 0x52, 0x54, 0xb1, 0x8d, 0x5a, 0xf1, 0x8a, 0xe2,
	0x77, 0xa6, 0x4a, 0x57, 0x06, 0xc7, 0xad, 0xe8, 0xa0, 0x33, 0x0a, 0x29, 0xdc, 0x03, 0x95, 0x1c,
	0x85, 0x7d, 0x04, 0x34, 0xe9, 0xaf, 0x34, 0xb1, 0xd6, 0x6e, 0x26, 0x61, 0xdf, 0x71, 0xb3, 0x09,
	0x76, 0xb0, 0x7f, 0x51, 0xd2, 0x21, 0x17, 0x01, 0x5a, 0xfc, 0x86, 0x92, 0x94, 0x61, 0x5c, 0xd2,
	0x1e, 0x17, 0x01, 0x7c, 0x02, 0x16, 0x33, 0x94, 0x2f, 0x78, 0x1c, 0xa2, 0x25, 0xcd, 0xfa, 0x27,
	0x4d, 0xac, 0x3f, 0x6f, 0x64, 0x69, 0x87, 0xe3, 0x66, 0xa5, 0xec, 0xab, 0x00, 0xee, 0xe7, 0xf3,
	0xd6, 0xa3, 0xfa, 0xfe, 0x9a, 0x3d, 0xff, 0xff, 0xdf, 0xe5, 0xa1, 0x67, 0xa3, 0xd2, 0x43, 0xd7,
	0x93, 0xba, 0x07, 0x80, 0xc7, 0xc2, 0x1e, 0x15, 0x92, 0x1e, 0x4b, 0xf4, 0x83, 0x26, 0xfd, 0x96,
	0x26, 0xd6, 0xca, 0xd4, 0xb6, 0xcf, 0x35, 0x8e, 0x3b, 0x61, 0x80, 0xf7, 0xc1, 0xa2, 0xa0, 0x43,
	0xc1, 0x24, 0xed, 0xf6, 0xfa, 0x11, 0xfa, 0xd1, 0x36, 0x6a, 0x4b, 0x2d, 0x33, 0x4d, 0xac, 0xea,
	0x65, 0x7f, 0x2e, 0xb2, 0x7b, 0xfd, 0xc8, 0x71, 0x41, 0x1e, 0x3d, 0xea, 0x47, 0xb0, 0x06, 0x0a,
	0x02, 0x0f, 0xd1, 0xcf, 0xda, 0xb8, 0x9c, 0x26, 0x16, 0x9c, 0x32, 0xe2, 0xa1, 0xe3, 0x2a, 0x09,
	0xdc, 0x01, 0xe5, 0x80, 0x46, 0x11, 0xf6, 0x29, 0x5a, 0xd6, 0xea, 0x6a, 0x9a, 0x58, 0xcb, 0x97,
	0xd5, 0xb9, 0xc0, 0x71, 0xc7, 0x52, 0xd5, 0x9f, 0xba, 0x0a, 0x2c, 0x92, 0xcc, 0x8b, 0xd0, 0x2f,
	0xda, 0x38, 0xa3, 0xbf, 0x0b, 0x8d, 0xe3, 0x4e, 0x18, 0xe0, 0x5b, 0x03, 0x94, 0xb2, 0xab, 0x82,
	0x90, 0xde, 0xd8, 0x20, 0x4d, 0xac, 0x97, 0xb3, 0x6f, 0x52, 0xfd, 0xf6, 0x37, 0x89, 0xd0, 0x43,
	0x1c, 0xf7, 0x65, 0xa3, 0x9e, 0x2d, 0x69, 0xab, 0x39, 0x59, 0x47, 0x1c, 0xd9, 0x75, 0x7b, 0xc0,
	0x45, 0x80, 0xfb, 0x8e, 0x9b, 0x67, 0x87, 0x2d, 0x00, 0x3c, 0x41, 0x71, 0x86, 0x40, 0x2b, 0xfa,
	0x3e, 0xae, 0xa6, 0x89, 0x65, 0x4d, 0x6e, 0xfc, 0x7c, 0x5b, 0x99, 0xd2, 0xc6, 0xd2, 0x71, 0x2b,
	0x79, 0xb0, 0x2b, 0x15, 0x23, 0x0e, 0xc9, 0x98, 0x51, 0xbd, 0x9e, 0x91, 0x2b, 0x33, 0x46, 0x1e,
	0xec, 0x4a, 0x38, 0x04, 0xe0, 0xa2, 0x15, 0xf4, 0xab, 0x66, 0x3c, 0x4f, 0x13, 0xab, 0x33, 0x7b,
	0x26, 0x5b, 0xb7, 0x9f, 0xc9, 0x38, 0x71, 0xfe, 0x35, 0x4b, 0x9c, 0x07, 0xbb, 0xb2, 0xb5, 0xfa,
	0xe5, 0xb3, 0x69, 0x7c, 0x38, 0x35, 0x8d, 0x93, 0x53, 0xd3, 0xf8, 0x74, 0x6a, 0x1a, 0xef, 0xce,
	0xcc, 0xb9, 0x93, 0x33, 0x73, 0xee, 0xe3, 0x99, 0x39, 0xf7, 0xa2, 0x18, 0x70, 0x42, 0xfb, 0x07,
	0x25, 0xfd, 0x6b, 0xb2, 0xfd, 0x35, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x08, 0xc3, 0x1e, 0x8a, 0x06,
	0x00, 0x00,
}

func (m *Task) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeletedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.DeletedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.Status != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if len(m.Statistics) > 0 {
		i -= len(m.Statistics)
		copy(dAtA[i:], m.Statistics)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Statistics)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if len(m.Raw) > 0 {
		i -= len(m.Raw)
		copy(dAtA[i:], m.Raw)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Raw)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if len(m.RewriteHls) > 0 {
		i -= len(m.RewriteHls)
		copy(dAtA[i:], m.RewriteHls)
		i = encodeVarintTask(dAtA, i, uint64(len(m.RewriteHls)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.TaskType) > 0 {
		i -= len(m.TaskType)
		copy(dAtA[i:], m.TaskType)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskType)))
		i--
		dAtA[i] = 0x6a
	}
	if m.OtherGroup != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.OtherGroup))
		i--
		dAtA[i] = 0x60
	}
	if m.OtherForm != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.OtherForm))
		i--
		dAtA[i] = 0x58
	}
	if m.OtherTag != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.OtherTag))
		i--
		dAtA[i] = 0x50
	}
	if m.OtherType != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.OtherType))
		i--
		dAtA[i] = 0x48
	}
	if len(m.TaskName) > 0 {
		i -= len(m.TaskName)
		copy(dAtA[i:], m.TaskName)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskName)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Cover) > 0 {
		i -= len(m.Cover)
		copy(dAtA[i:], m.Cover)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Cover)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.OtherId) > 0 {
		i -= len(m.OtherId)
		copy(dAtA[i:], m.OtherId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.OtherId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TaskPid) > 0 {
		i -= len(m.TaskPid)
		copy(dAtA[i:], m.TaskPid)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskPid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTask(dAtA []byte, offset int, v uint64) int {
	offset -= sovTask(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedTask(r randyTask, easy bool) *Task {
	this := &Task{}
	this.Id = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Id *= -1
	}
	this.TaskId = string(randStringTask(r))
	this.TaskPid = string(randStringTask(r))
	this.Uid = string(randStringTask(r))
	this.OtherId = string(randStringTask(r))
	this.Cover = string(randStringTask(r))
	this.TaskName = string(randStringTask(r))
	this.OtherType = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.OtherType *= -1
	}
	this.OtherTag = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.OtherTag *= -1
	}
	this.OtherForm = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.OtherForm *= -1
	}
	this.OtherGroup = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.OtherGroup *= -1
	}
	this.TaskType = string(randStringTask(r))
	this.Ciphertext = string(randStringTask(r))
	v1 := r.Intn(100)
	this.RewriteHls = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.RewriteHls[i] = byte(r.Intn(256))
	}
	v2 := r.Intn(100)
	this.Raw = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.Raw[i] = byte(r.Intn(256))
	}
	v3 := r.Intn(100)
	this.Message = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.Message[i] = byte(r.Intn(256))
	}
	v4 := r.Intn(100)
	this.Statistics = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.Statistics[i] = byte(r.Intn(256))
	}
	this.Status = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Status *= -1
	}
	this.CreatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreatedAt *= -1
	}
	this.UpdatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UpdatedAt *= -1
	}
	this.DeletedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.DeletedAt *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyTask interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTask(r randyTask) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTask(r randyTask) string {
	v5 := r.Intn(100)
	tmps := make([]rune, v5)
	for i := 0; i < v5; i++ {
		tmps[i] = randUTF8RuneTask(r)
	}
	return string(tmps)
}
func randUnrecognizedTask(r randyTask, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldTask(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldTask(dAtA []byte, r randyTask, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateTask(dAtA, uint64(key))
		v6 := r.Int63()
		if r.Intn(2) == 0 {
			v6 *= -1
		}
		dAtA = encodeVarintPopulateTask(dAtA, uint64(v6))
	case 1:
		dAtA = encodeVarintPopulateTask(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateTask(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateTask(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateTask(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateTask(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTask(uint64(m.Id))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.TaskPid)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.OtherId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Cover)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.TaskName)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.OtherType != 0 {
		n += 1 + sovTask(uint64(m.OtherType))
	}
	if m.OtherTag != 0 {
		n += 1 + sovTask(uint64(m.OtherTag))
	}
	if m.OtherForm != 0 {
		n += 1 + sovTask(uint64(m.OtherForm))
	}
	if m.OtherGroup != 0 {
		n += 1 + sovTask(uint64(m.OtherGroup))
	}
	l = len(m.TaskType)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.RewriteHls)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Raw)
	if l > 0 {
		n += 2 + l + sovTask(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 2 + l + sovTask(uint64(l))
	}
	l = len(m.Statistics)
	if l > 0 {
		n += 2 + l + sovTask(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovTask(uint64(m.Status))
	}
	if m.CreatedAt != 0 {
		n += 2 + sovTask(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 2 + sovTask(uint64(m.UpdatedAt))
	}
	if m.DeletedAt != 0 {
		n += 2 + sovTask(uint64(m.DeletedAt))
	}
	return n
}

func sovTask(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTask(x uint64) (n int) {
	return sovTask(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Task) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Task: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Task: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskPid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskPid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OtherId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cover", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cover = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherType", wireType)
			}
			m.OtherType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OtherType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherTag", wireType)
			}
			m.OtherTag = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OtherTag |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherForm", wireType)
			}
			m.OtherForm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OtherForm |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherGroup", wireType)
			}
			m.OtherGroup = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OtherGroup |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewriteHls", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewriteHls = append(m.RewriteHls[:0], dAtA[iNdEx:postIndex]...)
			if m.RewriteHls == nil {
				m.RewriteHls = []byte{}
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Raw", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...)
			if m.Raw == nil {
				m.Raw = []byte{}
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = append(m.Message[:0], dAtA[iNdEx:postIndex]...)
			if m.Message == nil {
				m.Message = []byte{}
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statistics", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Statistics = append(m.Statistics[:0], dAtA[iNdEx:postIndex]...)
			if m.Statistics == nil {
				m.Statistics = []byte{}
			}
			iNdEx = postIndex
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			m.DeletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTask(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTask
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTask
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTask
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTask
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTask        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTask          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTask = fmt.Errorf("proto: unexpected end of group")
)
